version: "3"
services:
  app:
    image: elixir:1.12-alpine
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    command: ash -c "cd app && mix do local.hex --force, local.rebar --force, deps.get, compile, phx.server"
