version: "3"
services:
  app:
    image: elixir:1.12-alpine
    restart: unless-stopped
    port:
      - "4000:4000"
    volumes:
      - ./:/workers
    command: mix do deps.get, compile, phx.server
