version: "3"
services:
  app:
    image: elixir:1.12-alpine
    restart: unless-stopped
    environment:
      - MIX_ENV=test
    volumes:
      - ./:/app
    command: ash -c "cd app && mix do local.hex --force, local.rebar --force, test"
